version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: garden-game
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Anhthu@91
      POSTGRES_DB: gardendb
    ports:
      - "1111:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
